---
title: "stanmodels"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

set.seed(1)
```

```{r}
library(rstan)
library(loo)
```

# Pooled Model

```{r}
data <- read.csv("../data/preprocessed_data.csv")
data
```

```{r}
x1 <- data[,'Continent']
x2 <- data[, 'Fullscale_IQ_Change']
x3 <- data[,'Schooling_Index']
x4 <- data[,'Decade']
```

## Model with Decade Index

```{r}
IQ <- list(N = length(x3),
           x1 = x4,
           y =  x2)
fit <- stan(file = '../models/pooled/pool.stan', data = IQ, seed=1)
m <- monitor(fit)
```

```{r}
ans <- extract(fit)
mean(ans$a)
mean(ans$b)
hist(ans$a)
hist(ans$b)
```

Convergence Analysis

```{r}
fit
check_hmc_diagnostics(fit)
```

```{r}
log_lik_1 <- extract_log_lik(fit, merge_chains = FALSE)
r_eff <- relative_eff(exp(log_lik_1))
loo_1 <- loo(log_lik_1, r_eff = r_eff)
loo_1$estimates
```

## Model with Schooling Index

```{r}
IQ <- list(N = length(x3),
           x1 = x3,
           y = x2)
fit <- stan(file = '../models/pooled/pool_schooling.stan', data = IQ, seed=1)
m <- monitor(fit)
```

```{r}
ans <- extract(fit)
mean(ans$a)
mean(ans$b)
hist(ans$a)
hist(ans$b)
```

Convergence Diagnostics

```{r}
fit
check_hmc_diagnostics(fit)
```

```{r}
log_lik_1 <- extract_log_lik(fit, merge_chains = FALSE)
r_eff <- relative_eff(exp(log_lik_1))
loo_1 <- loo(log_lik_1, r_eff = r_eff)
loo_1$estimates
```

## Model with Decade and Schooling Index

```{r}
IQ <- list(N = length(x3),
           x1 = x4,
           x2 = x3,
           y = x2)
fit <- stan(file = '../models/pooled/pool_adv.stan', data = IQ, seed=1)
m <- monitor(fit)
```

```{r}
ans <- extract(fit)
hist(ans$a)
mean(ans$a)
hist(ans$b)
mean(ans$b)
hist(ans$c)
```

Convergence Diagnostics

```{r}
fit
check_hmc_diagnostics(fit)
```

```{r}
log_lik_1 <- extract_log_lik(fit, merge_chains = FALSE)
r_eff <- relative_eff(exp(log_lik_1))
loo_1 <- loo(log_lik_1, r_eff = r_eff)
loo_1$estimates
```

```{r}
a <- mean(ans$a)
b <- mean(ans$b)
q_a <- quantile(ans$a, c(0.05, 0.95))
q_b <- quantile(ans$b, c(0.05, 0.95))

plot(x=x4, y=x3, type='p', ylim = c(-0.25,1))
lines(x4, a + b*x4, col ="red")
```

```{r}
a <- mean(ans$a)
b <- mean(ans$b)
q_a <- quantile(ans$a, c(0.05, 0.95))
q_b <- quantile(ans$b, c(0.05, 0.95))

plot(x=x4, y=x3, type='p', ylim=c(-6,6))
lines(x4, a + b*x4, col ="red")
lines(x4, q_a[1] + q_b[1]*x4, lty=3)
lines(x4, q_a[2] + q_b[2]*x4, col="blue", lty=3)
```

```{r}
dim(ans$b)
```

## Separate Model

```{r sep_simple}
data1 <- data[data$Continent == "Europe", ]
data2 <- data[data$Continent == "Oceania", ]
data3 <- data[data$Continent == "Africa", ]
data4 <- data[data$Continent == "Asia", ]
data5 <- data[data$Continent == "America", ]

length(data1$Decade)
sep_simple_data <- list(
  C = 5,
  N1 = length(data1$Decade),
  N2 = length(data2$Decade),
  N3 = length(data3$Decade),
  N4 = length(data4$Decade),
  N5 = length(data5$Decade),

  x1 = data1[, "Decade"],
  x2 = data2[, "Decade"],
  x3 = data3[, "Decade"],
  x4 = data4[, "Decade"],
  x5 = data5[, "Decade"],
  
  y1 = data1[, "Fullscale_IQ_Change"],
  y2 = data2[, "Fullscale_IQ_Change"],
  y3 = data3[, "Fullscale_IQ_Change"],
  y4 = data4[, "Fullscale_IQ_Change"],
  y5 = data5[, "Fullscale_IQ_Change"]
)

sep_simple_fit <- stan(file = 'sep_simple.stan',
                       data = sep_simple_data)
foo <- extract(sep_simple_fit)
m <- monitor(sep_simple_fit)
m$Rhat
```

```{r sep}
data1 <- data[data$Continent == "Europe", ]
data2 <- data[data$Continent == "Oceania", ]
data3 <- data[data$Continent == "Africa", ]
data4 <- data[data$Continent == "Asia", ]
data5 <- data[data$Continent == "America", ]

length(data1$Decade)
sep_data <- list(
  C = 5,
  N1 = length(data1$Decade),
  N2 = length(data2$Decade),
  N3 = length(data3$Decade),
  N4 = length(data4$Decade),
  N5 = length(data5$Decade),

  x1 = data1[, "Decade"],
  x2 = data2[, "Decade"],
  x3 = data3[, "Decade"],
  x4 = data4[, "Decade"],
  x5 = data5[, "Decade"],
  
  y1 = data1[, "Fullscale_IQ_Change"],
  y2 = data2[, "Fullscale_IQ_Change"],
  y3 = data3[, "Fullscale_IQ_Change"],
  y4 = data4[, "Fullscale_IQ_Change"],
  y5 = data5[, "Fullscale_IQ_Change"],
  
  z1 = data1[, "Schooling_Index"],
  z2 = data2[, "Schooling_Index"],
  z3 = data3[, "Schooling_Index"],
  z4 = data4[, "Schooling_Index"],
  z5 = data5[, "Schooling_Index"]
)

sep_fit <- stan(file = 'sep.stan',
                       data = sep_data)
foo <- extract(sep_fit)
m <- monitor(sep_fit)
m$Rhat
```

```{r_hier}
hier_fit <- stan(file='hier.stan', data=sep_data)
extract_hier_fit <- extract(hier_fit)
hier_m <- monitor(hier_fit)
hier_m$Rhat


```
